#
# Module manifest for module 'IROD'
#
# Generated by: Mark Orr
#
# Generated on: 2/2/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IROD.psm1'

# Version number of this module.
ModuleVersion = '1.0.2'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '62e1bc39-4701-483b-bf8d-1de40d950000'

# Author of this module
Author = 'Mark Orr'

# Company or vendor of this module
CompanyName = 'Mark Orr'

# Copyright statement for this module
Copyright = '(c) 2026 Mark Orr. All rights reserved.'

# Description of the functionality provided by this module
Description = 'IROD (Intune Remediation On Demand) - Trigger Intune Proactive Remediation scripts on-demand for single or multiple devices. Features include WPF GUI for device/script selection, script preview, favorites, parallel execution for large batches, CSV/TXT import, history logging, and export capabilities.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Microsoft.Graph.Authentication')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Invoke-IntuneRemediation', 'Configure-IROD', 'Clear-IRODConfig', 'Get-IntuneRemediationResults')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Intune', 'Remediation', 'MicrosoftGraph', 'EndpointManagement', 
                 'Windows', 'MEM', 'DeviceManagement', 'Proactive', 'Scripts',
                 'WPF', 'GUI', 'OnDemand', 'IROD', 'Microsoft365', 'MSGraph')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/markorr321/IROD/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/markorr321/IROD'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## v1.0.2

### New Features
- Dark/Light theme toggle (press T from main menu)
- Theme preference saved to %APPDATA%\IROD\settings.json

### Improvements
- File dialogs now use Windows Explorer GUI for import/export operations
- Import from File now has proper submenu with browse and template export options
- Template export moved before Graph connection (no auth needed)
- Import file validation before connecting to Graph
- Consistent menu structure throughout

## v1.0.0 - Initial Release

### Features
- Single device and multi-device remediation modes
- WPF GUI for script and device selection
- Script preview (view detection/remediation code)
- Favorites system for frequently used scripts
- Script description tooltips on hover
- Publisher and Version columns in script selector
- Parallel execution for batches over 50 devices (10 concurrent)
- Import devices from CSV/TXT files with template export
- History logging with 30-day retention
- Export remediation results to CSV
- Comprehensive help system with 9 topics
- Select ALL Devices option with safety confirmation
- Dark-themed modern UI

### Requirements
- PowerShell 5.1 or later
- Microsoft.Graph.Authentication module
- Graph permissions: DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementConfiguration.Read.All
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

